trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

steps:
- task: GoTool@0
  displayName: 'Install Go'
  inputs:
    version: '1.17'

- task: Go@0
  displayName: 'Go Get Dependencies'
  inputs:
    command: 'get'
    arguments: '-v -d'

- task: Go@0
  displayName: 'Go Build'
  inputs:
    command: 'build'
    arguments: '-o $(Build.ArtifactStagingDirectory)/myapp'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(tag)

- script: |
    # Run your tests and generate coverage report
    go test -coverprofile=reports/coverage.out ./...

    # Generate JUnit test report
    go test -json ./... | gotest2junit > reports/test-report.xml
  displayName: 'Run Tests'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'


